### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by slowmna** [puerts/EasyEditorPlugin#2]
引擎版本：5.3
Puer版本：1.0.5

![image](https://github.com/puerts/EasyEditorPlugin/assets/38640830/07a7597f-8999-4f95-800d-c4e3ea646a1e)

**Comment by chexiongsheng** [comment]
puerts要master版本才支持5.3

**Comment by huzhangyang** [comment]
master最新puerts也编不过，用9.4和8.4的v8都试了，都是上面截图的问题

**Comment by chexiongsheng** [comment]
> master最新puerts也编不过，用9.4和8.4的v8都试了，都是上面截图的问题

是有问题，@slowmna   反馈的都解决了，在这个[提交](https://github.com/puerts/EasyEditorPlugin/commit/072e71b0a4533c4cca8afddf14f6c9db00aedd67)，但还是有两个错误，报UE头文件的编译错误，也不知道哪里间接include了这文件，不知道怎么处理。

~~~bash
2>D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(779): error C2062: 意外的类型“void”
2>D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(780): error C2334: “{”的前面有意外标记；跳过明显的函数体
~~~

好像ue5.3有些api用了就报错，比如c++继承UUserWidget就会报错。

**Comment by chexiongsheng** [comment]
> > master最新puerts也编不过，用9.4和8.4的v8都试了，都是上面截图的问题
> 
> 是有问题，@slowmna 反馈的都解决了，在这个[提交](https://github.com/puerts/EasyEditorPlugin/commit/072e71b0a4533c4cca8afddf14f6c9db00aedd67)，但还是有两个错误，报UE头文件的编译错误，也不知道哪里间接include了这文件，不知道怎么处理。
> 
> ```shell
> 2>D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(779): error C2062: 意外的类型“void”
> 2>D:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformProcess.h(780): error C2334: “{”的前面有意外标记；跳过明显的函数体
> ```
> 
> 好像ue5.3有些api用了就报错，比如c++继承UUserWidget就会报错。

这个错误是新版本puerts的问题，已经解决。
